### ISSUE TITLE
[UC] CI tests of contracts do not get executed

### ISSUE THREAD

**Issue by myronrotter** [cp-ss2019/decentralized-energy-trading#126]
I just run the tests for the contracts of master branch on my local machine and realized that we did not fix the tests after adding `onlyHousehold` modifer for `getHousehold`. This is now fixed, refer to branch `fix/ci-test-contracts`.

After that I wondered why the CI tests pass successfully; this is, because they do not get executed. 
Tests run locally completly fine.

**Comment by minhi** [comment]
Might solve on the CI side by removing the quotation marks surrounding the test path:
`truffle test './test/contracts/*' --network develop` to
`truffle test ./test/contracts/* --network develop`
I feel like passing the path as a string prevents from, idk, bash to resolve the wildcard character.

**Comment by minhi** [comment]
Yeah, removing the quotation marks restores CI contract test functionality.
See https://github.com/cp-ss2019/decentralized-energy-trading/commit/7da0a666081cb15f5521c296daa71a843c00fcdb
