### ISSUE TITLE
[UC] Settlement (netting) does not update produce and consume

### ISSUE THREAD

**Issue by myronrotter** [cp-ss2019/decentralized-energy-trading#127]
As far as I see, the function `settle` only update the household stats for `renewableEnergy` and does not update the stats for `producedRenewableEnergy` and `consumedRenewableEnergy` such that after some consecutive settlements the values for `renewableEnergy` and producedRenewableEnergy` etc. are out of sync. 

Question: Is this the right behavior for settlement? I mean a energy transfer is not actually a produce/consume thing but otherwise the stored values do not make sens after some time.

Possible solution: Adjust `settle` such that it updates the above mentioned values or make the aggregated value `renewableEnergy` depend on the produced/consumed values.

**Comment by minhi** [comment]
Yes, it's an oversight that `producedRenewableEnergy` and `consumedRenewableEnergy` are not consistent to `renewableEnergy` after `settle`. No clue how we should approach this. Btw, we still found no usage for both variables, so maybe this is the right time to remove them?

**Comment by myronrotter** [comment]
I opened a PR #133 which solves this issue, but this PR is just a suggestion or a workaround.
Probably, later on we can remove both variables as mentioned above. @minhi please review PR #133.
