### ISSUE TITLE
[MS] Fix CLI flags in Mock Sensor

### ISSUE THREAD

**Issue by simonhuber95** [cp-ss2019/decentralized-energy-trading#128]
We currently have 2 flags corresponding to -e, one for the endpoint, and one for the energyBalance. This happened PR #121 
As there is currently no way to set the energyBalance one of the flags should be renamed.
- [ ] Rename flag in index.js
- [ ] Update corresponding README.md file

**Comment by myronrotter** [comment]
Completly, missed the `energyBalance`. Will fix.
