### ISSUE TITLE
[HHS][UC] Interaction

### ISSUE THREAD

**Issue by myronrotter** [cp-ss2019/decentralized-energy-trading#18]
The interaction/communication pattern between the HHS and the UC is pretty clear such that the HHS send transactions calling methods/functions of the UC. Nevertheless, we need to communicate which kind of data is sent within the transactions. Probably, there are two different approaches:

1. Send transactions (TXs) regarding energy consumption and production seperatly, e.g. there is one TX for setting consumption and and one for setting production.

2. Energy consumption and production is aggregated within the HHS, e.g. the gap/difference between consumption/production is sent within the TX.

**Comment by simonhuber95** [comment]
I think this point is crucial and we should thoroughly discuss it in our next meeting.
For transparency reason I would suggest to process the Overall Energy consumption within the smart contract. Therefore we could send a JSON object as data load to the contract containing all three smart meter values.

**Comment by myronrotter** [comment]
A JSON object is propably not the best way or we need some workaround for JSON objects. Lets discuss this in our meeting.

**Comment by myronrotter** [comment]
Refer to `IUtility.sol` for proper function calls/ interaction with `Utility.sol` contract.
