### ISSUE TITLE
[AN] [UC] Integrate UC into BlockReward

### ISSUE THREAD

**Issue by dakingha69** [cp-ss2019/decentralized-energy-trading#23]
## Task Description
As discussed in #9 we should for a first version use the approach to trigger the netting via the `BlockReward` contract. This can only be done when the `Utility` and `BlockReward` contracts are finished and the chain spec is correctly configured to use them.

## Acceptance Criteria
- [x] `reward` function triggers correct netting
- [x] interval is configurable via step duration and constant in `BlockReward` contract

**Comment by myronrotter** [comment]
First netting algorithm is in PR #36 and implements a simple FIFS settlement. Call `settle` function of `FifsUtility.col` contract to trigger settlement.
