### ISSUE TITLE
Style of code documentation

### ISSUE THREAD

**Issue by myronrotter** [cp-ss2019/decentralized-energy-trading#29]
As mentioned in pull-request #22. It would be great if we have a common style of (in-line and method/function) code documentation in the project. 

As @dakingha69 mentioned, one suggestion would be JSDoc.

**Comment by simonhuber95** [comment]
I think JSDoc Looks fine, we should include the [JSDoc Generator](https://github.com/jsdoc/jsdoc) in our Project. Let's have a quick talk about it tomorrow and then roll with it.
