### ISSUE TITLE
[AN] Add contracts when network starts

### ISSUE THREAD

**Issue by paguos** [cp-ss2019/decentralized-energy-trading#57]
**Background**
When the network starts some contracts should be deployed. It would be nice if this will happen in the background and no additional setup is required

**Acceptance Criteria**
Be able to deploy as many contracts as necessary when the blockchain network starts.

- [x] Implementation
- [x] Tests

**Comment by dakingha69** [comment]
Related to / Duplicate of #56

**Comment by paguos** [comment]
No need to implement this, all contracts will be deployed in the genesis file
