### ISSUE TITLE
[AN] Write script to setup network

### ISSUE THREAD

**Issue by paguos** [cp-ss2019/decentralized-energy-trading#58]
**Background**
It seems is not possible (or maybe to complicated) to deploy contracts with the genesis config. Maybe add a new native test setup, where the first node setups the network.

**Acceptance Criteria**
The first node should have the following functionality:

- [ ] Replace the `bootnode`
- [x] Mine blocks
- [x] Add contracts with truffle migrations 
- [x] Add the `ValidatorsSet` to `config.json` (so we can register more miners)
- [ ] Adapt tests

When solving this issue  #56 and #57 should be closed 👍

**Comment by dakingha69** [comment]
@paguos can you elaborate what you mean by 
> It seems not possible (or maybe too complicated) to deploy contracts with the genesis config.

?

Can't we put every contract into the genesis file for now? With hardcoded contract and owner addresses in the respective contracts?

**Comment by paguos** [comment]
@dakingha69 I did some research and I don't think that is possible ... If you know how, can you send me a link? 

I think the only approach we have is deploying them with the `truffle` migration. So it's easier...

**Comment by dakingha69** [comment]
I tested it out with the `BlockReward` contract already. You just specify the byte code of the contract at a given address in the chain spec (https://wiki.parity.io/Chain-specification). AFAIK this is the only option for using a custom `BlockReward` and `ValidatorSet` contract. As those contracts are then wired to the `Utility` contract they all have to be deployed this way when using the authority setup IMO.

We can use `truffle migrate` for other setups such as `ganache`.

**Comment by paguos** [comment]
Thanks! That is way better 👍

**Comment by paguos** [comment]
No need since contracts are deployed in the genesis file
