### ISSUE TITLE
[VS][UC][AN] Enable ownership transfer

### ISSUE THREAD

**Issue by dakingha69** [cp-ss2019/decentralized-energy-trading#60]
While working on the integration of the `Utility` contract into the `BlockReward` contract, it became an issue that we can not transfer the ownership of contracts. This will most likely also be an issue with the `OwnedValidatorSet`. The problem is that in the authority setup we specify all contracts as part of the genesis block via the chain spec file. All contracts that are deployed this way are deployed by the `SYSTEM_ADDRESS` which is basically the address of the "engine" and can not be controlled. Thus we have an owner that we can not control.

I think the easiest way to circumvent this is to make the ownership transferable by using a contract like this https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/ownership/Ownable.sol. This way we can transfer the ownership in the `BlockReward` contract to a controllable address.

**Comment by paguos** [comment]
If we are transferring them later, what is the point of deploying them in the genesis? I would just add them later ...

**Comment by dakingha69** [comment]
We are transferring only the ownership of the contracts later. With "them" you are referring to the contracts? Can you explain in detail how you would do this?

**Comment by paguos** [comment]
I was testing running a `truffle` migration on top of the network using the account of the first node ... Worked for the `Utility Contract` but I'm having trouble with the `ValidatorSet` 😠 💢 

I was thinking maybe the other nodes only join if the contracts are in the network or something in that direction

**Comment by dakingha69** [comment]
The problem is that we need as well as the address of the `BlockReward` and `ValidatorSet` contract in the chain spec. Also both contracts need to interact with the `Utility` contract and therefore need to know the address. How would you solve this without specifying the contracts in the chain spec?

**Comment by dakingha69** [comment]
Closed via #61
