### ISSUE TITLE
[MS] Implement Mock Data Generator

### ISSUE THREAD

**Issue by simonhuber95** [cp-ss2019/decentralized-energy-trading#7]
As we have no information about the kind of data whatsoever, we should just generate some random data samples

- [x] Draw Data Points from random distribution
- [x] Make generation generic, e.g amount of samples, min & max of samples, gaussian or uniform distribution
- [x] Add Timestamps to Data Points (Not necessary anymore, is done in DB)
- [x] Write Data Points into JSON Format
- [x] Make JSON Object public to other parts of the system
- [x] Send data periodically to HHS

**Comment by paguos** [comment]
You can use this dataset https://machinelearningmastery.com/how-to-load-and-explore-household-electricity-usage-data/ 

It would wise to clean it first 😉

**Comment by simonhuber95** [comment]
Looks like a nice Dataset and the cleanup should not take too long. But for now I would just sample some random data, which can also contain negative numbers to simulated energy surplus of a single Household. As I understand the dataset only contains Energy consumption.
