### ISSUE TITLE
[HHS] findOne({ "_id": id}) requires 'id' to be an object of class ObjectID.

### ISSUE THREAD

**Issue by jahandaniyal** [cp-ss2019/decentralized-energy-trading#91]
The **findByID()** function in `db_handler` does not work for simple string 'id' in the current patch. 
As a result, no match is found even for existing records.
To solve this, either we pass id as **ObjectID()** class object or we modify findByID() to wrap string 'id' values to ObjectID().
I will rebase the patch from 19th May on `hss-uc-request` branch, and send a PR.

**Comment by myronrotter** [comment]
@jahandaniyal as you mentioned for a possible solution. Assuming `id` is a number (this is the current state in the master branch), I would suggest to replace `.findOne({ _id: id })` with `.findOne({ "_id" : ObjectId(id.toString()) })` or `.findOne(ObjectId(id.toString()))` in method `findByID()`.
