### ISSUE TITLE
[HHS] GET /household-stats

### ISSUE THREAD

**Issue by dakingha69** [cp-ss2019/decentralized-energy-trading#98]
Depends on #97 so that the name of the endpoint `GET /household-stats` can be reused. This endpoint should basically return the result of `getHoushold(address _householdAddress)` of the utility contract.

**Comment by myronrotter** [comment]
Is almost done, refer to branch ` feature/hhs-get-household-stats`. Waiting for PR #108 and issue #97 to be solved in order to rebase and open PR for this issue.
