### ISSUE TITLE
[UC] Gas estimation for Utility Contract

### ISSUE THREAD

**Issue by paguos** [cp-ss2019/decentralized-energy-trading#99]
**Background**
It would nice to present some estimation of how much gas the `settle` method of the `Utility` contract consume.

**Acceptance Criteria** 
We should provide some numbers for a length between 10 and 200.000 households.

- [x] Write benchmark
- [x] Write `UtilityBenchmark` contract 
- [x] Output results in a `csv` file 
- [x] Write documentation
- [x] Create a fancy chart

This would be approached generating a _"mock"_ integration test environment that should be able to run on any machine.

**Comment by myronrotter** [comment]
This should be closed, refer to PR #122.
